### ISSUE TITLE
Cannot register barriers for Flabébé

### ISSUE THREAD

**Issue by dschu012** [Fvegini/Pokemon-Shuffle-Move-Helper#1]
The image name for Flabébé shows up incorrectly for me (I'm guessing because of the é). Because of so I cannot register barriers for the pokemon nor can I load the current board into shuffle move.

![image](https://github.com/Fvegini/Pokemon-Shuffle-Move-Helper/assets/1458109/fa3b9e65-d003-45c8-82f5-6b956b493c7c)

**Comment by Fvegini** [comment]
Thanks for the report!

I uploaded a new version, can you test to see if it worked? (On my machine it does)

**Comment by dschu012** [comment]
Worked great. Thanks.

**Comment by Fvegini** [comment]
@dschu012  Hey man, I saw your fork with the adb, nice job!
I don't use Android so I didn't had knowledge of this tool... but I downloaded an emulator and started some experiments!
I published a new branch with them if you want to take a look!
Are you on Shuffle discord or reddit? Send me dm if you wanna trade some ideas!

**Comment by dschu012** [comment]
Cool I'll check it out. Looks like you took what I had and expanded on it more/clean it up.
